Resources:
  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: $default
      CorsConfiguration:
        AllowOrigins:
          - https://<YOUR_CLOUDFRONT_DOMAIN>
        AllowMethods: ['GET', 'POST', 'OPTIONS']
        AllowHeaders: ['*']

  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub $giiku-backend-handler
      Handler: index.handler
      CodeUri: ../backend/dist
      Runtime: nodejs20.x
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        Root:
          Type: HttpApi
          Properties:
            Path: /
            Method: ANY
        Proxy:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY
